import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.scss";
import { Footer, Header } from "../shared/components/modules";

const notino = Nunito({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notino.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
